### ISSUE TITLE
considering unescaping msgid

### ISSUE THREAD

**Issue by AlexandreBonaventure** [Polyconseil/vue-gettext#59] opened 2017-11-19 17:52 UTC
**example**
```js
<translate>I’m big & fat</translate>
```
will result in this `msgid` =>
```js
I’m big &amp; fat
```
I'm using PoEdit which handles uft-8 and doesn't escape html characters my msgid is still 
```js
I’m big & fat
```
so it throws a warning `Untranslated msg found`

For now my workaround is to escape `&` => `&amp;` directly in my template but it will be a nice improvement IMO.

Thanks for this great package anyways

**Comment by kemar** [comment] 2018-02-28 12:26
I'm closing this because I cannot reproduce your issue, the `msgid` I got is not escaped.

Please provide a link to a [minimal reproduction](https://github.com/vuejs/vue-issue-helper/blob/428607cb6601bdee4c0eb46f3592cffd36fbc544/src/i18n/locales/en/repro-modal.md) of your problem if you're still experiencing it.

**Closed by kemar** 2018-02-28 12:26 UTC
